### ISSUE TITLE
Wrong values at knapsack?

### ISSUE THREAD

**Issue by Ronll** [yilenpan/algorithmofanalgorithm#1]
The built in test expects the solution for max weight 50 to be 146 but that does not make with the given values:

`var weights = {
  10: 40,
  20: 55,
  1: 1,
  5: 50
};`

The weight 5 is too "good" with 50, you would never want to pick 10, since two 5s will give you 100 while 10 -> 40;

Looking at the solution branch didn't help since it's using different values.

**Comment by yilenpan** [comment]
It's an either or, you can only take one item or not. You can't Duplicate
items

**Comment by Ronll** [comment]
Ok, made it clearer and added two test cases, I might add more later
#2

**Comment by yilenpan** [comment]
Awesome, thanks Ron!
